CDT-335 read header from schema
prratek/pipelinewise-tap-s3-csv pull request #1
Opened 2023-02-04 02:00 UTC by g9-mimizhao

- Adds optional config `infer_schema` that will force the tap to read the header from a provided catalog when no header is provided in a file

2023-02-16 19:58 UTC, prratek requested changes
had one suggestion, otherwise looks good

2023-02-16 19:58 UTC, prratek commented on tap_s3_csv/sync.py
> +    if config.get('infer_schema', None) and config['infer_schema'].lower() == "false":
if `infer_schema` is null then `config.get('infer_schema', None)` will evaluate to `None`. won't `None.lower()` fail with a `None type has no attribute lower()` or something like that?. if you change to something like this, the second part of the if won't ever evaluate if the first part is false.
```suggestion
    if 'infer_schema' in config and config['infer_schema'].lower() == "false":
```

2023-02-16 19:58 UTC, prratek commented on tap_s3_csv/sync.py
> +    if config.get('infer_schema', None) and config['infer_schema'].lower() == "false":
try it out thought. i didn't test my suggestion

2023-02-22 20:20 UTC, g9-mimizhao commented on tap_s3_csv/sync.py
> +    if config.get('infer_schema', None) and config['infer_schema'].lower() == "false":
Tried it out. Works on PS and Moat so I'm gonna say its good

2023-02-22 20:20 UTC, merged